version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - .docker/postgres_data:/var/lib/postgresql/data
