spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: admin
    password: 123123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
